[package]
name = "tokio-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
tokio = { version = "1.16.1", features = ["full"]  }
tokio-stream = { version = "0.1.8", features = ["sync"] }
